# yamllint disable-file
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "emr-vis"
  description: "Vis.js is a dynamic, browser based visualization library. The library is designed to be easy to use, handle large amounts of dynamic data, and enable manipulation of the data."
  title: "vis"
  tags:
    - emr
    - vis
    - graph
    - timeline
  annotations:
    backstage.io/techdocs-ref: "dir:."
    philips.com/techdocs-builder: "local"
    github.com/project-slug: philips-internal/emr-vis
    github.com/release: .
    github.com/advanced-security: .
  links:
    -   url: https://github.com/almende/vis.git
        title: Vis.js
        icon: docs
spec:
  type: "library"
  owner: "group:default/emr-eisenbahn-contributors"
  lifecycle: "production"
